config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= root_path %>">Samuel Cea</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item <%= 'active' if action_name == 'one' %>">
          <%= link_to 'one', root_path , class: 'nav-item nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if action_name == 'two' %>">
          <%= link_to 'two', pages_two_path , class: 'nav-item nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if action_name == 'three' %>">
          <%= link_to 'three', pages_three_path , class: 'nav-item nav-link' %>
        </li>
      </ul>
    </div>
  </nav>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/one.html.erb
<h1 class="text-center"> Samuel Cea</h1>

<div class="jumbotron text-center">
  <h1 class="display-4">Hola Mundo, soy Samuel</h1>
  <p class="lead">Esto es una simple app, no se ilusionen</p>
  <hr class="my-4">
  <p>A todos les gusta el helado</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/pages/three.html.erb
<h2 class="text-center "> Samuel Cea 3</h2>
<p class="text-center container">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ornare mi a nisl lobortis mattis. Donec accumsan, ex sit amet pretium facilisis, enim justo fermentum velit, nec imperdiet felis mauris vel mi. Phasellus bibendum fringilla magna in semper. Phasellus dapibus iaculis vestibulum. Etiam nec gravida risus. Cras ac nisl a quam pharetra fermentum nec a neque. Curabitur sapien turpis, consectetur eu velit in, tristique condimentum felis. Suspendisse potenti. Duis laoreet interdum vehicula. Nulla id arcu massa. Nulla rutrum neque id maximus dignissim. Curabitur erat dolor, blandit nec sodales quis, faucibus quis elit.</p>

app/views/pages/two.html.erb
<h1 class="text-center">Samuel Cea 2</h1>
<%= image_tag("screenshot.png", :alt => "Screenshot") %>